-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA IF NOT EXISTS flix;


CREATE TABLE IF NOT EXISTS flix.admin_movies
(
    id_admin_movie bigserial NOT NULL,
    created_by_user_id bigint,
    title text COLLATE pg_catalog."default" NOT NULL,
    release_year character varying(12) COLLATE pg_catalog."default",
    duration character varying(40) COLLATE pg_catalog."default",
    director text COLLATE pg_catalog."default",
    synopsis text COLLATE pg_catalog."default",
    cast_members text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    poster_url text COLLATE pg_catalog."default",
    trailer_url text COLLATE pg_catalog."default",
    rating numeric(3, 1),
    country text COLLATE pg_catalog."default",
    genres text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    platforms text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    moods text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Published'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_movies_pkey PRIMARY KEY (id_admin_movie)
);

CREATE TABLE IF NOT EXISTS flix.chat_conversations
(
    id_conversation bigserial NOT NULL,
    user_one_id bigint NOT NULL,
    user_two_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_conversations_pkey PRIMARY KEY (id_conversation)
);

CREATE TABLE IF NOT EXISTS flix.chat_messages
(
    id_message bigserial NOT NULL,
    id_conversation bigint NOT NULL,
    sender_user_id bigint NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id_message)
);

CREATE TABLE IF NOT EXISTS flix.comments
(
    id_comment bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    id_post bigint NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    parent_comment_id bigint,
    gif_url character varying(500) COLLATE pg_catalog."default",
    moderation_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    blocked_at timestamp without time zone,
    blocked_by_user_id bigint,
    CONSTRAINT comments_pkey PRIMARY KEY (id_comment)
);

CREATE TABLE IF NOT EXISTS flix.contact_messages
(
    id_contact_message bigserial NOT NULL,
    id_user bigint,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    email character varying(180) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(180) COLLATE pg_catalog."default" NOT NULL,
    category character varying(40) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contact_messages_pkey PRIMARY KEY (id_contact_message)
);

CREATE TABLE IF NOT EXISTS flix.email_verification_tokens
(
    id_verification serial NOT NULL,
    id_user integer NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id_verification)
);

CREATE TABLE IF NOT EXISTS flix.movie_review_likes
(
    id_like serial NOT NULL,
    id_review integer NOT NULL,
    id_user integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movie_review_likes_pkey PRIMARY KEY (id_like),
    CONSTRAINT uq_movie_review_likes UNIQUE (id_review, id_user)
);

CREATE TABLE IF NOT EXISTS flix.movie_reviews
(
    id_review serial NOT NULL,
    tmdb_movie_id integer NOT NULL,
    id_user integer NOT NULL,
    parent_review_id integer,
    content text COLLATE pg_catalog."default" NOT NULL,
    rating smallint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    moderation_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    blocked_at timestamp without time zone,
    blocked_by_user_id bigint,
    CONSTRAINT movie_reviews_pkey PRIMARY KEY (id_review)
);

CREATE TABLE IF NOT EXISTS flix.notifications
(
    id_notification bigserial NOT NULL,
    recipient_user_id bigint NOT NULL,
    actor_user_id bigint,
    notification_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_post bigint,
    id_comment bigint,
    metadata jsonb DEFAULT '{}'::jsonb,
    dedupe_key character varying(255) COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (id_notification),
    CONSTRAINT notifications_dedupe_key_key UNIQUE (dedupe_key)
);

CREATE TABLE IF NOT EXISTS flix.password_reset_tokens
(
    id_reset serial NOT NULL,
    id_user integer NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id_reset)
);

CREATE TABLE IF NOT EXISTS flix.payment_methods
(
    id_method character varying(80) COLLATE pg_catalog."default" NOT NULL,
    type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    category character varying(80) COLLATE pg_catalog."default",
    account_number text COLLATE pg_catalog."default",
    account_name character varying(160) COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    image_name character varying(180) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id_method)
);

CREATE TABLE IF NOT EXISTS flix.payment_packages
(
    package_code character varying(40) COLLATE pg_catalog."default" NOT NULL,
    package_name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    duration_months integer NOT NULL DEFAULT 1,
    price integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_packages_pkey PRIMARY KEY (package_code)
);

CREATE TABLE IF NOT EXISTS flix.payment_transactions
(
    id_transaction bigserial NOT NULL,
    id_user bigint NOT NULL,
    package_code character varying(40) COLLATE pg_catalog."default" NOT NULL DEFAULT 'premium'::character varying,
    package_name character varying(120) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Premium Bulanan'::character varying,
    duration_months integer NOT NULL DEFAULT 1,
    payment_method character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'qris'::character varying,
    payment_method_detail character varying(120) COLLATE pg_catalog."default",
    amount integer NOT NULL DEFAULT 0,
    admin_fee integer NOT NULL DEFAULT 0,
    total_amount integer NOT NULL DEFAULT 0,
    payer_name character varying(160) COLLATE pg_catalog."default",
    payer_email character varying(160) COLLATE pg_catalog."default",
    payer_phone character varying(60) COLLATE pg_catalog."default",
    ewallet_phone character varying(60) COLLATE pg_catalog."default",
    payment_proof text COLLATE pg_catalog."default",
    status character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    admin_note text COLLATE pg_catalog."default",
    verified_by_user_id bigint,
    verified_at timestamp without time zone,
    premium_started_at timestamp without time zone,
    premium_expired_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_transactions_pkey PRIMARY KEY (id_transaction)
);

CREATE TABLE IF NOT EXISTS flix.post_likes
(
    id_like bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    id_post bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_likes_pkey PRIMARY KEY (id_like),
    CONSTRAINT uq_post_like UNIQUE (id_user, id_post)
);

CREATE TABLE IF NOT EXISTS flix.post_poll_options
(
    id_option bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_poll bigint NOT NULL,
    option_text character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT post_poll_options_pkey PRIMARY KEY (id_option)
);

CREATE TABLE IF NOT EXISTS flix.post_poll_votes
(
    id_vote bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_poll bigint NOT NULL,
    id_option bigint NOT NULL,
    id_user bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_poll_votes_pkey PRIMARY KEY (id_vote),
    CONSTRAINT uq_post_poll_user UNIQUE (id_poll, id_user)
);

CREATE TABLE IF NOT EXISTS flix.post_polls
(
    id_poll bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_post bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_polls_pkey PRIMARY KEY (id_poll),
    CONSTRAINT post_polls_id_post_key UNIQUE (id_post)
);

CREATE TABLE IF NOT EXISTS flix.post_reactions
(
    id_reaction bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    id_post bigint NOT NULL,
    reaction_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_reactions_pkey PRIMARY KEY (id_reaction),
    CONSTRAINT uq_post_reaction UNIQUE (id_user, id_post)
);

CREATE TABLE IF NOT EXISTS flix.post_shares
(
    id_share bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_post bigint NOT NULL,
    id_user bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_shares_pkey PRIMARY KEY (id_share)
);

CREATE TABLE IF NOT EXISTS flix.post_views
(
    id_view bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_post bigint NOT NULL,
    id_user bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_views_pkey PRIMARY KEY (id_view)
);

CREATE TABLE IF NOT EXISTS flix.posts
(
    id_post bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    image_url text COLLATE pg_catalog."default",
    title character varying(300) COLLATE pg_catalog."default",
    tags text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    post_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'post'::character varying,
    moderation_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    blocked_at timestamp without time zone,
    blocked_by_user_id bigint,
    CONSTRAINT posts_pkey PRIMARY KEY (id_post)
);

CREATE TABLE IF NOT EXISTS flix.reports
(
    id_report bigserial NOT NULL,
    reporter_user_id bigint NOT NULL,
    report_type character varying(32) COLLATE pg_catalog."default" NOT NULL,
    category character varying(40) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    movie_review_id bigint,
    tv_series_review_id bigint,
    community_post_id bigint,
    community_comment_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    reported_user_id bigint,
    CONSTRAINT reports_pkey PRIMARY KEY (id_report)
);

CREATE TABLE IF NOT EXISTS flix.roles
(
    id_role bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id_role),
    CONSTRAINT roles_role_name_key UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS flix.tv_series_review_likes
(
    id_like serial NOT NULL,
    id_review integer NOT NULL,
    id_user integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tv_series_review_likes_pkey PRIMARY KEY (id_like),
    CONSTRAINT uq_tv_series_review_likes UNIQUE (id_review, id_user)
);

CREATE TABLE IF NOT EXISTS flix.tv_series_reviews
(
    id_review serial NOT NULL,
    tmdb_series_id integer NOT NULL,
    id_user integer NOT NULL,
    parent_review_id integer,
    content text COLLATE pg_catalog."default" NOT NULL,
    rating smallint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    moderation_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    blocked_at timestamp without time zone,
    blocked_by_user_id bigint,
    CONSTRAINT tv_series_reviews_pkey PRIMARY KEY (id_review)
);

CREATE TABLE IF NOT EXISTS flix.user_friends
(
    id_friend bigserial NOT NULL,
    requester_user_id bigint NOT NULL,
    addressee_user_id bigint NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'accepted'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_friends_pkey PRIMARY KEY (id_friend)
);

CREATE TABLE IF NOT EXISTS flix.user_watchlist
(
    id_watchlist bigserial NOT NULL,
    id_user bigint NOT NULL,
    media_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tmdb_id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    poster_url text COLLATE pg_catalog."default",
    release_year character varying(20) COLLATE pg_catalog."default",
    rating character varying(20) COLLATE pg_catalog."default",
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_watchlist_pkey PRIMARY KEY (id_watchlist),
    CONSTRAINT user_watchlist_id_user_media_type_tmdb_id_key UNIQUE (id_user, media_type, tmdb_id)
);

CREATE TABLE IF NOT EXISTS flix.users
(
    id_user bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_role bigint NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    profile_image_url text COLLATE pg_catalog."default",
    banner_image_url text COLLATE pg_catalog."default",
    email_verified boolean NOT NULL DEFAULT true,
    email_verified_at timestamp without time zone,
    is_active boolean NOT NULL DEFAULT true,
    deactivated_at timestamp without time zone,
    deactivated_by_user_id bigint,
    is_premium boolean NOT NULL DEFAULT false,
    payment_proof text COLLATE pg_catalog."default",
    subscription_plan character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'free'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id_user),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS flix.admin_movies
    ADD CONSTRAINT admin_movies_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.chat_conversations
    ADD CONSTRAINT chat_conversations_user_one_id_fkey FOREIGN KEY (user_one_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_one
    ON flix.chat_conversations(user_one_id);


ALTER TABLE IF EXISTS flix.chat_conversations
    ADD CONSTRAINT chat_conversations_user_two_id_fkey FOREIGN KEY (user_two_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_two
    ON flix.chat_conversations(user_two_id);


ALTER TABLE IF EXISTS flix.chat_messages
    ADD CONSTRAINT chat_messages_id_conversation_fkey FOREIGN KEY (id_conversation)
    REFERENCES flix.chat_conversations (id_conversation) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.chat_messages
    ADD CONSTRAINT chat_messages_sender_user_id_fkey FOREIGN KEY (sender_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.comments
    ADD CONSTRAINT comments_blocked_by_user_id_fkey FOREIGN KEY (blocked_by_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.comments
    ADD CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id)
    REFERENCES flix.comments (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.comments
    ADD CONSTRAINT fk_comments_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.comments
    ADD CONSTRAINT fk_comments_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.contact_messages
    ADD CONSTRAINT contact_messages_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_email_verification_tokens_id_user
    ON flix.email_verification_tokens(id_user);


ALTER TABLE IF EXISTS flix.movie_review_likes
    ADD CONSTRAINT movie_review_likes_id_review_fkey FOREIGN KEY (id_review)
    REFERENCES flix.movie_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_movie_review_likes_id_review
    ON flix.movie_review_likes(id_review);


ALTER TABLE IF EXISTS flix.movie_review_likes
    ADD CONSTRAINT movie_review_likes_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.movie_reviews
    ADD CONSTRAINT movie_reviews_blocked_by_user_id_fkey FOREIGN KEY (blocked_by_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.movie_reviews
    ADD CONSTRAINT movie_reviews_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.movie_reviews
    ADD CONSTRAINT movie_reviews_parent_review_id_fkey FOREIGN KEY (parent_review_id)
    REFERENCES flix.movie_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_movie_reviews_parent_review_id
    ON flix.movie_reviews(parent_review_id);


ALTER TABLE IF EXISTS flix.notifications
    ADD CONSTRAINT notifications_actor_user_id_fkey FOREIGN KEY (actor_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.notifications
    ADD CONSTRAINT notifications_id_comment_fkey FOREIGN KEY (id_comment)
    REFERENCES flix.comments (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.notifications
    ADD CONSTRAINT notifications_id_post_fkey FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.notifications
    ADD CONSTRAINT notifications_recipient_user_id_fkey FOREIGN KEY (recipient_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_id_user
    ON flix.password_reset_tokens(id_user);


ALTER TABLE IF EXISTS flix.payment_transactions
    ADD CONSTRAINT payment_transactions_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_payment_transactions_user
    ON flix.payment_transactions(id_user);


ALTER TABLE IF EXISTS flix.payment_transactions
    ADD CONSTRAINT payment_transactions_verified_by_user_id_fkey FOREIGN KEY (verified_by_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.post_likes
    ADD CONSTRAINT fk_post_likes_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_likes
    ADD CONSTRAINT fk_post_likes_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_options
    ADD CONSTRAINT fk_post_poll_options_poll FOREIGN KEY (id_poll)
    REFERENCES flix.post_polls (id_poll) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_votes
    ADD CONSTRAINT fk_post_poll_votes_option FOREIGN KEY (id_option)
    REFERENCES flix.post_poll_options (id_option) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_votes
    ADD CONSTRAINT fk_post_poll_votes_poll FOREIGN KEY (id_poll)
    REFERENCES flix.post_polls (id_poll) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_votes
    ADD CONSTRAINT fk_post_poll_votes_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_polls
    ADD CONSTRAINT fk_post_polls_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS post_polls_id_post_key
    ON flix.post_polls(id_post);


ALTER TABLE IF EXISTS flix.post_reactions
    ADD CONSTRAINT fk_post_reactions_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_reactions
    ADD CONSTRAINT fk_post_reactions_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_shares
    ADD CONSTRAINT fk_post_shares_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_shares
    ADD CONSTRAINT fk_post_shares_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.post_views
    ADD CONSTRAINT fk_post_views_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_post_views_id_post
    ON flix.post_views(id_post);


ALTER TABLE IF EXISTS flix.post_views
    ADD CONSTRAINT fk_post_views_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_post_views_id_user
    ON flix.post_views(id_user);


ALTER TABLE IF EXISTS flix.posts
    ADD CONSTRAINT fk_posts_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.posts
    ADD CONSTRAINT posts_blocked_by_user_id_fkey FOREIGN KEY (blocked_by_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.reports
    ADD CONSTRAINT reports_community_comment_id_fkey FOREIGN KEY (community_comment_id)
    REFERENCES flix.comments (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.reports
    ADD CONSTRAINT reports_community_post_id_fkey FOREIGN KEY (community_post_id)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.reports
    ADD CONSTRAINT reports_movie_review_id_fkey FOREIGN KEY (movie_review_id)
    REFERENCES flix.movie_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.reports
    ADD CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.reports
    ADD CONSTRAINT reports_reporter_user_id_fkey FOREIGN KEY (reporter_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.reports
    ADD CONSTRAINT reports_tv_series_review_id_fkey FOREIGN KEY (tv_series_review_id)
    REFERENCES flix.tv_series_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.tv_series_review_likes
    ADD CONSTRAINT tv_series_review_likes_id_review_fkey FOREIGN KEY (id_review)
    REFERENCES flix.tv_series_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tv_series_review_likes_id_review
    ON flix.tv_series_review_likes(id_review);


ALTER TABLE IF EXISTS flix.tv_series_review_likes
    ADD CONSTRAINT tv_series_review_likes_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.tv_series_reviews
    ADD CONSTRAINT tv_series_reviews_blocked_by_user_id_fkey FOREIGN KEY (blocked_by_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.tv_series_reviews
    ADD CONSTRAINT tv_series_reviews_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.tv_series_reviews
    ADD CONSTRAINT tv_series_reviews_parent_review_id_fkey FOREIGN KEY (parent_review_id)
    REFERENCES flix.tv_series_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tv_series_reviews_parent_review_id
    ON flix.tv_series_reviews(parent_review_id);


ALTER TABLE IF EXISTS flix.user_friends
    ADD CONSTRAINT user_friends_addressee_user_id_fkey FOREIGN KEY (addressee_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_friends_addressee
    ON flix.user_friends(addressee_user_id);


ALTER TABLE IF EXISTS flix.user_friends
    ADD CONSTRAINT user_friends_requester_user_id_fkey FOREIGN KEY (requester_user_id)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_friends_requester
    ON flix.user_friends(requester_user_id);


ALTER TABLE IF EXISTS flix.user_watchlist
    ADD CONSTRAINT user_watchlist_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (id_role)
    REFERENCES flix.roles (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

END;
